# Generated by Django 5.1.5 on 2025-02-05 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NERText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Default text')),
            ],
        ),
        migrations.CreateModel(
            name='NERResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.CharField(default='Unknown entity', max_length=255)),
                ('entity_type', models.CharField(default='Unknown type', max_length=255)),
                ('occurrences', models.IntegerField(default=0)),
                ('ner_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='new_ner_app.nertext')),
            ],
        ),
    ]
