# Generated by Django 5.1.5 on 2025-02-04 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NERResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('entity', models.CharField(max_length=255)),
                ('entity_type', models.CharField(max_length=255)),
                ('occurrences', models.IntegerField()),
            ],
        ),
    ]
