# Generated by Django 5.1.5 on 2025-02-05 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ner_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NERText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='Default text')),
            ],
        ),
        migrations.RemoveField(
            model_name='nerresult',
            name='text',
        ),
        migrations.AlterField(
            model_name='nerresult',
            name='entity',
            field=models.CharField(default='Unknown entity', max_length=255),
        ),
        migrations.AlterField(
            model_name='nerresult',
            name='entity_type',
            field=models.CharField(default='Unknown type', max_length=255),
        ),
        migrations.AlterField(
            model_name='nerresult',
            name='occurrences',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nerresult',
            name='ner_text',
            field=models.ForeignKey(default='Default text', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='ner_app.nertext'),
            preserve_default=False,
        ),
    ]
